--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-1岿-23-2020   
--------------------------------------------------------
@D:\glim\TABLES\ADMIN.sql
@D:\glim\TABLES\BANID.sql
@D:\glim\TABLES\COMMENTS.sql
@D:\glim\TABLES\FILELIST.sql
@D:\glim\TABLES\GUDOK.sql
@D:\glim\TABLES\MEMBER.sql
@D:\glim\TABLES\WRITEBOARD.sql
@D:\glim\DATA_TABLE\ADMIN.sql
@D:\glim\DATA_TABLE\BANID.sql
@D:\glim\DATA_TABLE\COMMENTS.sql
@D:\glim\DATA_TABLE\FILELIST.sql
@D:\glim\DATA_TABLE\GUDOK.sql
@D:\glim\DATA_TABLE\MEMBER.sql
@D:\glim\DATA_TABLE\WRITEBOARD.sql
@D:\glim\INDEXES\SYS_C007574.sql
@D:\glim\INDEXES\SYS_C007547.sql
@D:\glim\CONSTRAINTS\MEMBER.sql
@D:\glim\CONSTRAINTS\WRITEBOARD.sql
