REM INSERTING into WRITEBOARD
SET DEFINE OFF;
Insert into WRITEBOARD (SEQ,NICKNAME,CATEGORY,VIEWS,WRITEDATE,TITLE) values (193,'sky','inmun',6,'20/01/22','테스트');
Insert into WRITEBOARD (SEQ,NICKNAME,CATEGORY,VIEWS,WRITEDATE,TITLE) values (192,'sky','sisa',519,'20/01/22','시사이슈');
Insert into WRITEBOARD (SEQ,NICKNAME,CATEGORY,VIEWS,WRITEDATE,TITLE) values (195,'sky','inmun',9,'20/01/22','테스트해봅시다');
